azure:
  application-insights:
    instrumentation-key: 7bcb7386-6660-48ae-902b-3a6cbc9b1537
    enabled: true
    web:
      enabled: true
    logger:
      level: trace

authorization:
  secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
  expiration: 28800

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    version: OPENAPI_3_0