name: Android Debug CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Unit tests
        run: bash ./gradlew test --stacktrace

  apk:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build apk
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Create app artifact
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Upload file to file.io
        id: upload
        uses: JantHsueh/upload-file-action@master
        with:
          url: https://file.io/
          forms: '{"autoDelete":"true"}'
          fileForms: '{"file":"app/build/outputs/apk/debug/app-debug.apk"}'
      - name: Convert json response to object
        id: output
        run: |
          echo ::set-output name=output::'${{ steps.upload.outputs.output }}' | ConvertFrom-Json
      - name: Upload debug apk to appetize
        uses: JongtaekChoi/github-action-appetize@master
        id: apppetize_upload
        with:
          APPETIZE_TOKEN: ${{ secrets.APPETIZE_TOKEN }} 
          # PUBLICKEY: "public_key"
          FILE_URL: '${{ steps.output.outputs.output.link }}'
          PLATFORM: "android"
