name: Android Debug CI

on:
  push:
    branches: [ dev, fix/upload-apk ]
  pull_request:
    branches: [ dev ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Unit tests
        run: bash ./gradlew test --stacktrace

  apk:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build apk
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Create app artifact
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Upload apk to appetize
        id: upload
        uses: JantHsueh/upload-file-action@master
        with:
          url: ${{ format('https://{0}@api.appetize.io/v1/apps', secrets.APPETIZE_TOKEN) }}
          forms: ${{ format('{ "platform":"android", "publicKey":"{0}" }', secrets.APPETIZE_KEY) }}
          fileForms: '{"file":"app/build/outputs/apk/debug/app-debug.apk"}'
