name: Dev CLI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ dev ]
    paths:
      - 'app/**'
      - 'build.gradle.kts'
      - 'gradle/**'
  pull_request:
    branches: [ dev ]
    paths:
      - 'app/**'
      - 'build.gradle.kts'
      - 'gradle/**'
  workflow_dispatch:

jobs:
  analyze:
    name: Run detekt
    runs-on: ubuntu-latest

    steps:
      - uses: natiginfo/action-detekt-all@1.23.1

  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.0

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Unit tests
        run: ./gradlew :app:test --stacktrace

      - name: Build apk
        run: ./gradlew :app:assembleDebug --stacktrace

      - name: Create app artifact
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Upload apk to appetize
        id: upload
        uses: JantHsueh/upload-file-action@master
        with:
          url: ${{ format('https://{0}@api.appetize.io/v1/apps/g0z1zuju8b88vf6bq40xx9t8ym', secrets.APPETIZE_TOKEN) }}
          forms: '{"platform":"android"}'
          fileForms: '{"file":"app/build/outputs/apk/debug/app-debug.apk"}'
