name: Dev CLI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.4.0

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Unit tests
        run: ./gradlew test --stacktrace

  analyze:
    name: Run detekt
    runs-on: ubuntu-latest

    steps:
      - uses: natiginfo/action-detekt-all@1.22.0

  apk:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.4.0

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build apk
        run: ./gradlew assembleDebug --stacktrace

      - name: Create app artifact
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Upload apk to appetize
        id: upload
        uses: JantHsueh/upload-file-action@master
        with:
          url: ${{ format('https://{0}@api.appetize.io/v1/apps/g0z1zuju8b88vf6bq40xx9t8ym', secrets.APPETIZE_TOKEN) }}
          forms: '{"platform":"android"}'
          fileForms: '{"file":"app/build/outputs/apk/debug/app-debug.apk"}'
