name: Release CLI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'build.gradle.kts'
      - 'gradle/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'build.gradle.kts'
      - 'gradle/**'
  workflow_dispatch:

jobs:
  apk:
    name: Build Release APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build release
        run: ./gradlew :app:assembleRelease --stacktrace

      - name: Upload apk
        uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: app/build/outputs/apk/release/app-release.apk