name: Release CLI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  apk:
    name: Build Release APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.0

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build release
        run: ./gradlew assembleRelease --stacktrace

      - name: Upload apk
        uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: app/build/outputs/apk/release/app-release.apk
